<?php

namespace Unlok\WordFinder\Tests;

use \ReflectionClass;
use PHPUnit\Framework\TestCase;

abstract class BaseTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    protected function factory($class, $arguments = [])
    {
        $built = new ReflectionClass($class);
        return $built->newInstanceArgs($arguments);
    }
}
